In [2]:
import pandas as pd
data=pd.read_csv("user_positive_games.csv")
data.head()

             steamid     app_id
0  76561197960265841  [1825540]
1  76561197960265890   [201070]
2  76561197960267068  [1677970]
3  76561197960267615    [98900]
4  76561197960268079   [446110]

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195200 entries, 0 to 195199
Data columns (total 2 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   steamid  195200 non-null  int64
 1   app_id   195200 non-null  object
dtypes: int64(1), object(1)
memory usage: 3.0+ MB

In [4]:
import ast

data['app_id'] = data['app_id'].apply(ast.literal_eval)  # Convert to lists
data = data[data['app_id'].apply(lambda x: len(x) > 1)]  # Filter
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20978 entries, 10 to 195162
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   steamid  20978 non-null  int64
 1   app_id   20978 non-null  object
dtypes: int64(1), object(1)
memory usage: 491.7+ KB

In [5]:
!pip install mlxtend==0.21.0

Requirement already satisfied: mlxtend==0.21.0 in /usr/local/lib/python3.11/dist-packages (0.21.0)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.11/dist-packages (from mlxtend==0.21.0) (1.15.3)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.11/dist-packages (from mlxtend==0.21.0) (2.0.2)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.11/dist-packages (from mlxtend==0.21.0) (2.2.2)
Requirement already satisfied: scikit-learn>=1.0.2 in /usr/local/lib/python3.11/dist-packages (from mlxtend==0.21.0) (1.6.1)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from mlxtend==0.21.0) (3.10.0)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.11/dist-packages (from mlxtend==0.21.0) (1.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from mlxtend==0.21.0) (75.2.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend==0.21.0) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend==0.21.0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend==0.21.0) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend==0.21.0) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend==0.21.0) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend==0.21.0) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend==0.21.0) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend==0.21.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24.2->mlxtend==0.21.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24.2->mlxtend==0.21.0) (2025.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.0.2->mlxtend==0.21.0) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend==0.21.0) (1.17.0)

In [6]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules
transactions = data['app_id'].tolist() # Convert the 'app_id' column to a list of transactions

te = TransactionEncoder()
te_ary = te.fit_transform(transactions)
df = pd.DataFrame(te_ary, columns=te.columns_)
df.head()

,20,1250,1520,1670,1700,1900,2200,2270,2280,2360,...,3487940,3489640,3491290,3495070,3505820,3505840,3505850,3505880,3505890,3505910
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [10]:
frequent_itemsets = apriori(df, min_support=0.001, use_colnames=True) # Lowered min_support
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)

In [8]:
print(rules)

          antecedents        consequents  antecedent support  \
0            (425580)           (456750)            0.002336
1            (456750)           (425580)            0.002097
2           (1361320)           (425580)            0.002145
3            (425580)          (1361320)            0.002336
4           (1361320)           (456750)            0.002145
5            (456750)          (1361320)            0.002097
6            (932500)           (965830)            0.001764
7            (965830)           (932500)            0.001716
8            (968290)           (965830)            0.001335
9            (965830)           (968290)            0.001716
10          (3204840)          (3206090)            0.001621
11          (3206090)          (3204840)            0.001478
12          (3313560)          (3285370)            0.002050
13          (3285370)          (3313560)            0.002383
14  (1361320, 425580)           (456750)            0.001239
15  (1361320, 456750)           (425580)            0.001573
16   (425580, 456750)          (1361320)            0.001478
17          (1361320)   (425580, 456750)            0.002145
18           (425580)  (1361320, 456750)            0.002336
19           (456750)  (1361320, 425580)            0.002097

    consequent support   support  confidence        lift  leverage  conviction
0             0.002097  0.001478    0.632653  301.631725  0.001473    2.716513
1             0.002336  0.001478    0.704545  301.631725  0.001473    3.376710
2             0.002336  0.001239    0.577778  247.359637  0.001234    2.362889
3             0.002145  0.001239    0.530612  247.359637  0.001234    2.125865
4             0.002097  0.001573    0.733333  349.633333  0.001569    3.742135
5             0.002145  0.001573    0.750000  349.633333  0.001569    3.991420
6             0.001716  0.001239    0.702703  409.480480  0.001236    3.357864
7             0.001764  0.001239    0.722222  409.480480  0.001236    3.593650
8             0.001716  0.001335    1.000000  582.722222  0.001332         inf
9             0.001335  0.001335    0.777778  582.722222  0.001332    4.493994
10            0.001478  0.001239    0.764706  517.483871  0.001237    4.243720
11            0.001621  0.001239    0.838710  517.483871  0.001237    6.189951
12            0.002383  0.001668    0.813953  341.502326  0.001664    5.362189
13            0.002050  0.001668    0.700000  341.502326  0.001664    3.326501
14            0.002097  0.001144    0.923077  440.097902  0.001141   12.972733
15            0.002336  0.001144    0.727273  311.361781  0.001140    3.658102
16            0.002145  0.001144    0.774194  360.911828  0.001141    4.419072
17            0.001478  0.001144    0.533333  360.911828  0.001141    2.139691
18            0.001573  0.001144    0.489796  311.361781  0.001140    1.956917
19            0.001239  0.001144    0.545455  440.097902  0.001141    2.197273

In [9]:
for index, row in rules.iterrows():
    antecedents = list(row['antecedents'])
    consequents = list(row['consequents'])

    print(f"{antecedents[0]} > {consequents[0]}")

425580 > 456750
456750 > 425580
1361320 > 425580
425580 > 1361320
1361320 > 456750
456750 > 1361320
932500 > 965830
965830 > 932500
968290 > 965830
965830 > 968290
3204840 > 3206090
3206090 > 3204840
3313560 > 3285370
3285370 > 3313560
1361320 > 456750
1361320 > 425580
425580 > 1361320
1361320 > 425580
425580 > 1361320
456750 > 1361320